### ISSUE TITLE
有关python2和python3的问题

### ISSUE THREAD

**Issue by giantsugar** [honmaple/maple-bbs#13]
stringtype和unicodetype应该怎么修改

**Comment by giantsugar** [comment]
<img width="998" alt="2018-03-03 6 06 38" src="https://user-images.githubusercontent.com/20023845/36933078-4acd6d4a-1f0e-11e8-8983-0710b4ab6798.png">

**Comment by honmaple** [comment]
现在只支持python3的版本，python2的话需要做很多修改和兼容，目前还没有时间

**Comment by giantsugar** [comment]
但是我确实是在python3的版本下运行的源代码 也是这个报错

**Comment by honmaple** [comment]
python3下我这运行是正常的，你这config.py怎么会放到`python3.6/site-packages`下？

**Comment by giantsugar** [comment]
我用pycharm打开源代码后 。 config.py直接就进入到了python3.6/site-packages下 是因为这个原因么？

**Comment by honmaple** [comment]
正常(按照README)来讲config.py应该和runserver.py是同一级目录下

**Comment by giantsugar** [comment]
嗯  那这个config文件应该是在哪里 我可不可以复制到和runserver.py在同一级目录下 我现在复制python3.6/site-packages下的congfig.py过去还是会出现这个报错

**Comment by honmaple** [comment]
Reopen if need.
