### ISSUE TITLE
MIDDLEWARE不生效

### ISSUE THREAD

**Issue by hezkvectory** [honmaple/maple-bbs#14]
在config.py中配置MIDDLEWARE = ["test.common.middleware.GlobalMiddleware"]，但是GlobalMiddleware的preprocess_request没有执行，请问这个怎么解决

**Comment by honmaple** [comment]
确认一下 `test/common/middleware.py` 文件是否存在，另外 `test` 必须是一个python package

**Comment by honmaple** [comment]
Reopen if need.
