### ISSUE TITLE
两天时间跑通了，所有坑都走了一遍！

### ISSUE THREAD

**Issue by huangtao00** [honmaple/maple-bbs#17]
踩坑笔记（希望对大家有用）：
http://www.meyoublog.com/posts/go-forums/

**Comment by honmaple** [comment]
谢谢支持, 验证码可以传递字体变量的 , Captcha(font="font path")

**Comment by yaakovazat** [comment]
http://www.meyoublog.com/posts/go-forums/ 你的这个网站地址打开实在是太慢了～～～
