### ISSUE TITLE
404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by yangql881012** [honmaple/maple-bbs#19]
你好，我运行后报这个错，这是什么原因呢，谢谢

**Comment by honmaple** [comment]
可能是因为子域名的原因，默认使用了子域名，应该访问 `forums.localhost:8000`

**Comment by yangql881012** [comment]
找到问题了，是子域名的问题，我现在能访问了，不过http:// forums.localhost:8000/admin的时候，啥都不显示，只有最上面有一个首页。这种事啥原因呢。谢谢



yangql881012@sina.com
 
From: honmaple
Date: 2018-05-31 18:13
To: honmaple/maple-bbs
CC: yangql881012; Author
Subject: Re: [honmaple/maple-bbs] 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. (#19)
可能是因为子域名的原因，默认使用了子域名，应该访问 forums.localhost:8000

**Comment by honmaple** [comment]
admin页面需要登陆，并且是管理员帐号才能访问, `python runserver.py create_user` 默认创建的就是管理员

**Comment by yangql881012** [comment]
用户创建了，

id username email password is_superuser is_confirmed register_time last_login
1 admin admin@126.com pbkdf2:sha256:50000$UfnWzYks$6b7de00b10023e7cecd1225ad4fd219152cca3eb709354d8ad3edf12f8ccd323 1 1 2018-05-30 09:34:50 2018-05-30 09:34:50



yangql881012@sina.com
 
From: honmaple
Date: 2018-06-01 15:20
To: honmaple/maple-bbs
CC: yangql881012; Author
Subject: Re: [honmaple/maple-bbs] 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. (#19)
admin页面需要登陆，并且是管理员帐号才能访问, python runserver.py create_user 默认创建的就是管理员

**Comment by honmaple** [comment]
Reopen if need.

**Comment by penglong1994** [comment]
我有同样的问题，可以帮忙解决下吗？
