### ISSUE TITLE
访问forums.localhost:8000/admin一直提示404

### ISSUE THREAD

**Issue by 52lemon** [honmaple/maple-bbs#23]
使用admin账号登陆，访问管理后台，一直访问不了，还请楼主帮忙看看是什么原因

**Comment by honmaple** [comment]
看一下配置里的`SERVER_NAME`是否是`localhost:8000`, 以及`SUBDOMAIN`配置是否为`True`，如果还不行可以注释`forums/admin/views.py`文件里的
```
    def is_accessible(self):
        return super_permission.can()
```
看看是否是权限问题

**Comment by 52lemon** [comment]
主掉了上面的接口
`Connected to pydev debugger (build 182.4323.49)
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
pydev debugger: process 22719 is connecting

 * Debugger is active!
 * Debugger PIN: 138-770-163
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: '_pydevd_frame_eval.pydevd_frame_evaluator.get_bytecode_while_frame_eval'
RecursionError: maximum recursion depth exceeded while calling a Python object`现在是启动服务访问admin直接服务就停了，报的是上面的错误

**Comment by 52lemon** [comment]
bleach==2.1.2
cffi==1.11.4
cssmin==0.2.0
Flask==0.12.2
Flask-Admin==1.5.2
Flask-Assets==0.12
Flask-Avatar==0.1.3
Flask-Babel
Flask-Caching==1.3.2
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Maple==0.5.3
Flask-Migrate==1.8.0
flask-msearch==0.1.5
Flask-Principal==0.4.0
Flask-SQLAlchemy==2.2
Flask-WTF==0.14.2
gunicorn==19.9.0
hiredis==0.2.0
Jinja2==2.10
jsmin==2.2.0
misaka==2.1.0
Pillow==5.1.0
psycopg2==2.7.5
Pygments==2.1
pytz==2018.3
redis==2.10.5
SQLAlchemy==1.2.11
Whoosh==2.7.4
WTForms==2.1
mysqlclient=1.3.13
我是用的是python3.6部分包版本做了升级和你的不太一样

**Comment by honmaple** [comment]
卸载`flask-babelex`即可

**Comment by 52lemon** [comment]
楼主太棒了，果然是这个包的坑，卸载了就好了
