### ISSUE TITLE
测试发现注册邮件无法接收，关注节点后无法取消，同时后台管理点击create时会报错

### ISSUE THREAD

**Issue by penglong1994** [honmaple/maple-bbs#26]
File "E:\pengl\lib\site-packages\flask_admin\contrib\sqla\fields.py", line 103, in <listcomp>
    self._object_list = [(text_type(get_pk(obj)), obj) for obj in query]
  File "E:\pengl\lib\site-packages\flask_admin\contrib\sqla\fields.py", line 300, in get_pk_from_identity
    cls, key = identity_key(instance=obj)
ValueError: too many values to unpack (expected 2)
点击后报如上错误

点击关注的节点也会出现报错。

望解答fix

**Comment by penglong1994** [comment]
问题全部解决，但是存在其他问题，比如
上传头像后，没有做到全局更改，部分地方的头像仍然是字母；
发帖时，一个版块同一个用户只能发一个帖子，目前是这样的；关注用户那一块还是存在问题；
使用搜索功能总是返回搜索没有返回结果（即使有对应的帖子）

**Comment by penglong1994** [comment]
还存在编辑个人资料不成功的问题。。

**Comment by honmaple** [comment]
非常感谢你的报道
> 上传头像后，没有做到全局更改，部分地方的头像仍然是字母  

这个可能是缓存的原因，也有可能是部分模板没有使用到修改后的头像，这个我检查一下
> 一个版块同一个用户只能发一个帖子;编辑个人资料不成功

可能还是因为缓存

> 使用搜索功能总是返回搜索没有返回结果  

这是因为分词的选择，如果需要对中文更加友好的支持，可以使用`jieba`分词

**Comment by honmaple** [comment]
Reopen if needed
