### ISSUE TITLE
templates目录下缺少HTML文件（maple/auth.html）

### ISSUE THREAD

**Issue by JNULYD** [honmaple/maple-bbs#29]
templates目录下的auth目录下面的login.html从templates目录下的maple目录下面导入了auth.html文件（{% import 'maple/auth.html' as auth %}），但实际上maple目录下面没有auth.html文件。导入的地方也是不可点击跳转状态。

**Comment by honmaple** [comment]
`maple/auth.html`是使用了`flask-maple`这个扩展，具体可以看[flask-maple](https://github.com/honmaple/flask-maple)，此项目下`maple/*.html`属于覆盖原有文件
