### ISSUE TITLE
请教访问admin页面问题

### ISSUE THREAD

**Issue by supermario1990** [honmaple/maple-bbs#32]
访问admin页面显示是这样的，请问有可能是哪里出问题了？

![image](https://user-images.githubusercontent.com/8428531/59565112-9b2b5500-9081-11e9-9a55-715131e96160.png)

**Comment by supermario1990** [comment]
知道了

**Comment by Aopodo** [comment]
你好，我也遇到了这个问题，请问你最后是怎么解决的？
