### ISSUE TITLE
PermissionError: [Errno 13] Permission denied问题

### ISSUE THREAD

**Issue by chengzequn** [honmaple/maple-bbs#37]
您好，最近在搞您的这个bbs,但是运行python3 runserver.py 后遇到以下错误说权限被拒绝，希望得到您的帮助，谢谢
python3 runserver.py 
/home/b3log/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
runserver.py:28: DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'. This import is deprecated as of version 0.15 and will be removed in 1.0.
  app.wsgi_app = ProxyFix(app.wsgi_app)
 * Serving Flask app "forums" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "runserver.py", line 173, in <module>
    app.run()
  File "/home/b3log/anaconda3/lib/python3.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/b3log/anaconda3/lib/python3.7/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
PermissionError: [Errno 13] Permission denied

**Comment by honmaple** [comment]
你换一个端口试试，修改`config.py`里`SERVER_NAME`
