### ISSUE TITLE
启动访问报redis的错误，能关闭redis这个功能吗？

### ISSUE THREAD

**Issue by chengzequn** [honmaple/maple-bbs#40]
启动访问/admin报redis的错误，能关闭redis这个功能吗？
redis.exceptions.ConnectionError

redis.exceptions.ConnectionError: Error 97 connecting to localhost:6379. Address family not supported by protocol.

**Comment by honmaple** [comment]
因为有部分统计信息，还有缓存是放到redis里的，关闭redis会导致程序无法正常运行，目前还没有好的方式来禁止redis
