### ISSUE TITLE
Address family not supported by protocol.

### ISSUE THREAD

**Issue by chengzequn** [honmaple/maple-bbs#41]
启动访问页面报以下错误

redis.exceptions.ConnectionError

redis.exceptions.ConnectionError: Error 97 connecting to localhost:6379. Address family not supported by protocol.

**Comment by chengzequn** [comment]
redis配置
# Use cache
CACHE_TYPE = 'simple'
CACHE_DEFAULT_TIMEOUT = 60
CACHE_KEY_PREFIX = 'cache:'
CACHE_REDIS_HOST = 'xxx.redis.rds.aliyuncs.com'
CACHE_REDIS_PORT = '6379'
CACHE_REDIS_PASSWORD = ''
CACHE_REDIS_DB = 2

**Comment by honmaple** [comment]
config.py里需要配置REDIS，`CACHE_REDIS_HOST`是缓存相关的
```
REDIS = {host='localhost', port=6379, 'db': 1, 'password': '', 'decode_responses': True}
```
