### ISSUE TITLE
The CSRF session token is missing？

### ISSUE THREAD

**Issue by chengzequn** [honmaple/maple-bbs#42]
你好，首页可以正常访问，但是当我注册或者登录的时候报400的错误，无法登录，The CSRF session token is missing
谢谢

**Comment by honmaple** [comment]
请先检查相关依赖版本是否一致，然后打开网页右键查看源代码，正常会显示
![image](https://user-images.githubusercontent.com/12235570/68272687-6440f480-009f-11ea-91f5-3e2dc4f8440c.png)

**Comment by honmaple** [comment]
可能图片显示不出来，正常会显示这么一段js
```
<script type="text/javascript">
var g = {
   csrftoken: "...."
};
</script>
```
