### ISSUE TITLE
启动访问页面404

### ISSUE THREAD

**Issue by chengzequn** [honmaple/maple-bbs#47]
启动访问localhost:8000/admin页面显示404，
启中配置如下
SERVER_NAME = '0.0.0.0:8000'
SUBDOMAIN = {'forums': False, 'docs': False}

**Comment by chengzequn** [comment]
安装的anaconda3.7,利用conda创建的虚拟环境，

**Comment by ronin-sws** [comment]
这个项目你部署成功了么 @chengzequn

**Comment by chengzequn** [comment]
> 这个项目你部署成功了么 @chengzequn
没有，当时是公司要弄的，但是相应的权限没有给，最后就没有弄了
