### ISSUE TITLE
请问该论坛支持国际化吗

### ISSUE THREAD

**Issue by yujianFresh** [honmaple/maple-bbs#5]

**Comment by honmaple** [comment]
目前只有中文和英文两种语言,如果想要支持其他语言，可以更改 **manager.py** 中的 **babel_init** ,将 **zh** 更改为你想要的语言,然后运行 python manager.py babel_init,会在translations下生成对应的目录，修改po文件后python manager.py babel_compile就行

另外默认语言使用浏览器请求的language,具体可以看这里 [https://github.com/honmaple/maple-bbs/blob/master/forums/extension.py](https://github.com/honmaple/maple-bbs/blob/master/forums/extension.py)

**Comment by yujianFresh** [comment]
请问是同时支持两种语言吗，还是中英文只能支持一种

**Comment by honmaple** [comment]
不是太懂你什么意思，界面显示的语言是根据浏览器请求的语言显示，或者已登录用户可以通过设置更改界面语言，不过目前两种情况都之支持中文和英文
