### ISSUE TITLE
请问file and code templates 中的last update如何设置？

### ISSUE THREAD

**Issue by tianyuningmou** [honmaple/maple-bbs#6]
# Created: 2016-10-25 22:01:29 (CST)
# Last Update:星期六 2017-4-15 20:38:39 (CST)
#          By:
# Description:

请不吝赐教，微信：vip15097403106

**Comment by honmaple** [comment]
我使用的是emacs，具体可以看这 [https://github.com/honmaple/dotfiles/blob/master/emacs.d/lisp/init-auto-insert.el](https://github.com/honmaple/dotfiles/blob/master/emacs.d/lisp/init-auto-insert.el)

另外,无关的issue我先关闭了
