### ISSUE TITLE
there ara problem about CAPTCHA

### ISSUE THREAD

**Issue by learnerzhang** [honmaple/maple-bbs#8]
register the account，CAPTCHA cannot load.  and the project is available on py3

**Comment by honmaple** [comment]
I can't understand your question, please follow and check if it' normal [captcha](https://forums.honmaple.org/captcha)

**Comment by honmaple** [comment]
reopen if needed

**Comment by huangtao00** [comment]
@learnerzhang u can solve this problem like this:

> #remove pillow
pip uninstall pillow
#install requirements
sudo apt-get install libjpeg-dev
sudo apt-get install libpng-dev

#reinstall pillow
pip install pillow
