### ISSUE TITLE
请问config.py应该如何配置？

### ISSUE THREAD

**Issue by xzenggit** [honmaple/maple-bbs#9]
你好，

我在运行代码的时候出现了以下错误：

```
redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.
```

我猜想可能是config.py配置的问题，能不能给个具体的例子呢？或者稍微说一下 config.py配置中应该注意的地方。我需要先自己创建一个数据库吗？如果我用默认的sqlite的话，代码会自动生成数据库吗？新手问的问题可能比较弱智哈~多谢多谢~

另外，我发现现在的代码须在python3和flask-maple==0.5.2的环境下才能运行，希望更新一下相应的信息，谢谢~

**Comment by honmaple** [comment]
这是因为 `redis` 密码不对, 可以使用 sqlite, 不过需要 `python manager.py init_db`才能创建数据库

我自己默认使用的python3所以没太注意，flask-maple我之前更新了版本，但忘记修改requestments.txt了,多谢提醒，我改一下

**Comment by honmaple** [comment]
reopen if needed
